# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_time', models.DateTimeField()),
                ('country', models.CharField(max_length=1024)),
                ('location', models.CharField(max_length=1024)),
                ('event_type', models.CharField(max_length=1024)),
                ('mail_category', models.CharField(max_length=1024)),
                ('next_office', models.CharField(max_length=1024)),
                ('extra_info_col1', models.CharField(max_length=1024)),
                ('extra_info_col2', models.CharField(max_length=1024)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsaggregator.Shipment')),
            ],
        ),
    ]
